# Generated by Django 2.2 on 2020-07-04 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='id_hotel',
            new_name='hotel_id',
        ),
    ]
